<?php

echo '<style>.right.mb-1 {
    margin-bottom: 15px !important;
}

.mbtm3, select {
    margin-bottom: 13px !important;
    height: 26px !important;
    width: 100%;
}</style>';
/*
Pupilsight, Flexible & Open School System
*/

use Pupilsight\Forms\Form;
use Pupilsight\Forms\DatabaseFormFactory;

if (isActionAccessible($guid, $connection2, '/modules/Transport/transport_invoice_assign_manage_add.php') == false) {
    //Acess denied
    echo "<div class='error'>";
    echo __('You do not have access to this action.');
    echo '</div>';
} else {
    //Proceed!
    $page->breadcrumbs
        ->add(__('Manage Invoice Assign'), 'transport_fee.php')
        ->add(__('Add Invoice Assign'));

    $editLink = '';
    if (isset($_GET['editID'])) {
        $editLink = $_SESSION[$guid]['absoluteURL'].'/index.php?q=/modules/Transport/transport_invoice_assign_manage_add.php&id='.$_GET['editID'];
    }
    if (isset($_GET['return'])) {
        returnProcess($guid, $_GET['return'], $editLink, null);
    }
    echo '<h2>';
    echo __('Invoice Generated By Class');
    echo '</h2>';
    //if(isset($_REQUEST['sid'])?$id=$_REQUEST['sid']:$id="" );
    $pupilsightSchoolYearID = '';
    if (isset($_GET['pupilsightSchoolYearID'])) {
        $pupilsightSchoolYearID = $_GET['pupilsightSchoolYearID'];
    }
    if ($pupilsightSchoolYearID == '' or $pupilsightSchoolYearID == $_SESSION[$guid]['pupilsightSchoolYearID']) {
        $pupilsightSchoolYearID = $_SESSION[$guid]['pupilsightSchoolYearID'];
        $pupilsightSchoolYearName = $_SESSION[$guid]['pupilsightSchoolYearName'];
    }

    $data = array('pupilsightSchoolYearID' => $pupilsightSchoolYearID);
    $sql = 'SELECT name FROM pupilsightSchoolYear WHERE pupilsightSchoolYearID=:pupilsightSchoolYearID';
    $result = $pdo->executeQuery($data, $sql);

    $sqlp = 'SELECT pupilsightProgramID, name FROM pupilsightProgram ';
    $resultp = $connection2->query($sqlp);
    $rowdataprog = $resultp->fetchAll();

    $program=array();  
    $program2=array();  
    $program1=array(''=>'Select Program');
    foreach ($rowdataprog as $dt) {
        $program2[$dt['pupilsightProgramID']] = $dt['name'];
    }
    $program= $program1 + $program2;  

    $sqlc = 'SELECT a.pupilsightYearGroupID, a.name, b.id, GROUP_CONCAT(b.schedule_id) AS fsid FROM pupilsightYearGroup AS a LEFT JOIN trans_schedule_assign_class AS b ON a.pupilsightYearGroupID = b.pupilsightYearGroupID GROUP BY a.pupilsightYearGroupID ORDER BY a.pupilsightYearGroupID ASC ';
    $resultc = $connection2->query($sqlc);
    $rowdatacls = $resultc->fetchAll();

    // echo '<pre>';
    // print_r($rowdatacls);
    // echo '</pre>';
    $classes=array();  
    foreach ($rowdatacls as $dt) {
        if(empty($dt['id'])){
            $content = '<span style="color:red;">(Not Assign)</span>';
        } else {
            $content = '';
        }
        $classes[$dt['pupilsightYearGroupID']] = $content.' '.$dt['name'];
    }
     

    $form = Form::create('program', $_SESSION[$guid]['absoluteURL'].'/modules/'.$_SESSION[$guid]['module'].'/transport_invoice_assign_manage_addProcess.php');
    $form->setFactory(DatabaseFormFactory::create($pdo));

    $form->addHiddenValue('address', $_SESSION[$guid]['address']);
    //$form->addHiddenValue('fn_fee_invoice_id', $id);

    $row = $form->addRow();
            $row->addLabel('pupilsightProgramID', __('Organisation'));
            $row->addSelect('pupilsightProgramID')->fromArray($program)->required()->placeholder();

    $row = $form->addRow();
    $row->addLabel('pupilsightYearGroupID', __(''));
        $col = $row->addColumn()->setClass('newdes mbtm2');
            $col->addLabel('name', __('Class'));
            foreach($rowdatacls as $k => $cl){
                if(empty($cl['id'])){
                    $content = '<span style="color:red;">(Not Assign)</span>';
                    $col->addCheckbox('pupilsightYearGroupID[class]['.$cl['pupilsightYearGroupID'].']')->setDisabled('1')->description(__($content.' '.$cl['name']));
                } else {
                    $content = '';
                    $col->addCheckbox('pupilsightYearGroupID[class]['.$cl['pupilsightYearGroupID'].']')->description(__($content.' '.$cl['name']));
                }
               
            }
        $col = $row->addColumn()->setClass('newdes');
            $col->addLabel('invoice_title', __('Transport Schedule'));
            foreach($rowdatacls as $k => $cl){
                if(!empty($cl['fsid'])){
                    $sqlchk = 'SELECT GROUP_CONCAT(DISTINCT b.transport_schedule_id) as fid FROM fn_fee_invoice_class_assign AS a LEFT JOIN fn_fee_invoice AS b ON a.fn_fee_invoice_id = b.id WHERE a.pupilsightYearGroupID = '.$cl['pupilsightYearGroupID'].' ';
                    $resultchk = $connection2->query($sqlchk);
                    $chkstrid = $resultchk->fetch();
                    $fid = $chkstrid['fid'];
                    if(!empty($fid)){
                        $sqlf = 'SELECT id, schedule_name FROM trans_schedule WHERE id IN ('.$cl['fsid'].') AND id NOT IN ('.$fid.') ';
                    } else {
                        $sqlf = 'SELECT id, schedule_name FROM trans_schedule WHERE id IN ('.$cl['fsid'].') ';
                    }
                    $resultf = $connection2->query($sqlf);
                    $rowdatafees = $resultf->fetchAll();
                    if(!empty($rowdatafees)){
                        $feesStructure = array();
                        $feesStructure1 = array(''=>'Select Schedule');
                        $feesStructure2 = array();
                        foreach ($rowdatafees as $dt) {
                            $feesStructure2[$dt['id']] = $dt['schedule_name'];
                        }
                        $feesStructure = $feesStructure1 + $feesStructure2;

                        $col->addSelect('pupilsightYearGroupID[structure]['.$cl['pupilsightYearGroupID'].']')->fromArray($feesStructure)->setClass('mbtm3'); 
                    } else {
                        $feesStructure = array();
                        $col->addLabel('pupilsightYearGroupID[structure]['.$cl['pupilsightYearGroupID'].'', __(''))->setClass('hidelevel mbtm3');
                    }
                } else {
                    $feesStructure = array();
                    $col->addLabel('pupilsightYearGroupID[structure]['.$cl['pupilsightYearGroupID'].'', __(''))->setClass('hidelevel mbtm3');
                }
                
                 
            }
        
        //     $row->addLabel('pupilsightYearGroupID', __('Class'));

        // $row->addCheckbox('pupilsightYearGroupID[]')->fromArray($classes)->required()->addCheckAllNone();

    // $row = $form->addRow();
    //     $row->addLabel('pupilsightRollGroupID', __('Section'));
    //     $row->addSelectRollGroup('pupilsightRollGroupID', $pupilsightSchoolYearID)->required();

        
    $row = $form->addRow();
        $row->addFooter();
        $row->addSubmit();

    echo $form->getOutput();

}
